### ISSUE TITLE
Cielo LIO Payment Remote Java Client

### ISSUE THREAD

**Issue by frekele** [DeveloperCielo/LIO-SDK-API-Integracao-Remota-v1-Java#1]
Hi,

I think this project very dirty and inconsistent, so I decided to create a new java client.

I created a client for use in Java  Desktop and Web Applications, based  on cielo documentation.
The project is built with RESTEasy 3.1.x.
I am using integrated with ERP/PDV in my company.
The goal is for other developers in the community to use and help with issues and PRs.

https://github.com/frekele/cielo-lio-remote-client

This client already published in maven central.

#### Maven dependency:
```xml
<dependency>
    <groupId>org.frekele.cielo</groupId>
    <artifactId>cielo-lio-remote-client</artifactId>
    <version>1.0.0</version>
</dependency>
```

#### Gradle dependency:
```gradle
compile 'org.frekele.cielo:cielo-lio-remote-client:1.0.0'
```

Thank you.

**Comment by SthefaniaMFerri** [comment]
Hello frekele,

We are very happy to share your project with us!

We would like to take more details and understand about your experience.
Can you send us some information please? (If you prefer to use the email **cielo@sensedia.com** or open a ticket in **https://devcielo.zendesk.com/hc/en/requests/new**)

Your name:
Your E-mail:
Business / Company:
Description your application:
Country:

Thank you!
,Sthefania Ferri
Developer Experience Cielo LIO
