### ISSUE TITLE
Duvidas Integração Remota Cielo Lio

### ISSUE THREAD

**Issue by frekele** [DeveloperCielo/LIO-SDK-API-Integracao-Remota-v1-Java#3]
Bom dia,

conforme conversei com a Sthefania Ferri nessa Issue no Github. 
https://github.com/DeveloperCielo/LIO-SDK-API-Integracao-Remota-v1-Java/issues/1 
Eu criei um rest client java para fazer as solicitações Rest Remote Order Management da Cielo Lio.

Como estou no processo de desenvolvimento/homologação da comunicação o OrderManagement, fiquei preocupado em relação a manutenção do componente, 
então resolvi abrir o codigo e liberar para que outros se beneficiem e com isso vou ter um feedback melhor caso ocorra um erro ou algo mude e etc;

Esse mesmo componente vai ser usado na minha empresa integrado a um ERP/PDV online. 
Posteriormente vamos lançar um e-commerce e estamos estudando a ideia de integrar também com a API cielo-ecommerce (talvez eu crie um componente para ele também).

Bom, existem algumas coisas(pontos) que não estão claro para mim, tanto na documentação quando nos codigos de exemplo no GitHub.

- O 1º ponto é o modelo json da transação (payment_fields): 
no manual de desenvolvimento consta que no tópico (POST - Adicionar uma Transação): 
```json
{ 
"id": "442bbdbe-41c8-4e22-83ee-e1a849ed3cb5", 
"external_id": "0b37f0d8-017a-4b11-91b9-ec1bb3e8fed3", 
"status": "CONFIRMED", 
"terminal_number": "12345678", 
"authorization_code": "008619", 
"number": "672836", 
"amount": 2000, 
"transaction_type": "PAYMENT", 
"payment_fields": { 
"primary_product_name": "CREDITO", 
"secondary_product_name": "A VISTA", 
"number_of_quotas": 0 
}, 
"card": { 
"brand": "VISA", 
"mask": "************5487" 
} 
} 
```

Já no tópico seguinte (Notificações de Mudanças na Order) consta: 
```json
{ 
"id": "c7b1dfc39f59436fbc55db8b4e360a96", 
"order_id": "ede8f84a8b8645cb8e576a593c25c6ed", 
"type": "TRANSACTION_ADDED", 
"transaction": { 
"id": "ede8f84a8b8645cb8e576a593c25c6ed", 
"transaction_type": "PAYMENT", 
"status": "CONFIRMED", 
"terminal_number": "928273921", 
"card": { 
"brand": "VISA", 
"bin": "490172", 
"last": "7897" 
}, 
"number": "1234589", 
"authorization_code": "22388292", 
"payment_product": { 
"number": 928282, 
"name": "CREDITO", 
"sub": { 
"number": 928282, 
"name": "A VISTA" 
} 
}, 
"amount": 5000, 
"created_at": "20151020T13:13:29.000Z", 
"updated_at": "20151022T12:13:29.000Z" 
} 
}
```
Em um exemplo a estrutura é diferente da outra, entendo que um é o exemplo de inclusao e outro do push notification (callback). 

Mas no codigo gerado de exemplo: https://github.com/DeveloperCielo/LIO-SDK-API-Integracao-Remota-v1-Java/blob/master/src/main/java/io/swagger/client/model/OrdersTransactions.java 
é usado o segundo formato com payment_product e sub.

Então fiz a tentatica de Post em meus testes com os dois formatado, o segundo formato não funciona pois necessita informar o campo mask dentro do card.

Nas inclusões com o primeiro modelo 'payment_fields', funciona porem ao fazer as consultar, este mesmo campo não retorna.

Acredito que as informaçoes de pagamento como o cartao, a forma de pagamento e as parcelas, é muito importante, pois esse retorno vai ser carregado no PDV para o display e impressao dos comprovantes e NFC-e.

Outra detalhe também em relação aos manual, o push (callback) não está retornando no modelo especificado.

O meu componente é construido usando o Travis-CI, durante o build eles faz os testes de integração e todos os callbacks retornam para a seguinte URL de captação: 
https://hookbin.com/bin/Z8abPwXo

Se você acessar e olhar os registros verá o que eu estou dizendo, iclusive os Ids de ordem e transacao retornam dentro do campo uuid e nao dentro do id, isso gera confusão.

- O 2º ponto é em relação ao status 'CANCELED' da ordem: 
No manual e nos exemplos do cliclo de vida do pedido, não consigo entender onde este status entra, em que momento ele acontece realmente.

- O 3º ponto é o campo unit_of_measure: 
Na documentação está escrito que os valores são estes: 
Unidade de medida (EACH, HOURS, DAYS, SECONDS, CRATE_OF_12, SIX_PACK, GALLON e LITRE); 
Porem eu fico em duvida se estes valores são constantes, ou são somente exemplos, pois geralmente no mercado o pessoal usa unidades de medida como UN, CX, PCT e etc.. 
Caso sejam constantes, seria interessante contemplar as 'Tabela Padrão de Unidades de Medidas Comerciais' criado receita federal para uso na NF-e. 
http://www.nfe.fazenda.gov.br/portal/exibirArquivo.aspx?conteudo=RY8TPoGpyMY=

- O 4º ponto é sobre as Bandeiras: 
Nos exemplos que encontrei parece que não contempla todos os cartões, não consegui reconhecer todas os valores possiveis das bandeiras. 
Na classe de exemplo temos: https://github.com/DeveloperCielo/LIO-SDK-API-Integracao-Remota-v1-Java/blob/master/src/main/java/io/swagger/client/model/Card.java 
Porem faltam outras bandeiras, como Sorocred, Hipercard, Discover, Alelo entre outros. 
Fico em duvida quais são os valores corretos que iram retornar, para minha aplicação trabalhar com isso, por exemplo AMERICAN EXPRESS retorna AMEX, 
DINERS CLUB, retorna DINERS. 
Seria possivel adicionar a documentação todas as constantes possiveis.

- O 5º ponto é sobre os campos number e authorization_code da transação: 
Na documentação consta que eles são do Tipo Number, mas nos exemplos é apresentado em String e com zeros a esquerda. 
A minha duvida é como devo tratar estes campos, visto que se eu tratar eles como numerico, os zero a esquerda serão perdidos, e não sei se isso é importante para os comprovantes e etc.

- O 6º ponto é o campo external_id da transacao: 
Não está bem claro se é o Id da ordem, ou um id qualquer externo, pois quando eu crio a transacao e seto o external_id o mesmo retorna null depois.

Bom acho que são estas duvidas que estão me travando no momento para dar continuidade ao meu componente.

Estou a disposição para ajudar no que for possivel;

Obrigado desde Já.

**Comment by magnocosta** [comment]
Olá @frekele,

Sou parte do time de desenvolvimento da Cielo LIO e vou tentar te ajudar nesses pontos.

**Sobre a parte 1:** 
A diferença no momento que você cria a transação e recebe uma notificação acontece, por conta de que na notificação precisamos informar o status da ordem e não apenas dados da transação. 

A idéia é que a URL de callback, configurada pelo desenvolvedor, seja uma espécie de ouvinte, onde tudo o que acontece na ordem poderia ser ouvido, cabe então o cliente decidir tratar ou não esses eventos. Olhando por esse ponto acredito que objetos diferentes para cada uma dessas operações faz sentido.

Sobre a parte do objeto transação dentro da notificação ser diferente do objeto transação enviado no momento do cadastro. Eles não deveriam ser diferentes, vou checar com o pessoal aqui qual foi a motivação mas acredito ser um problema. Nesse ponto o que mais te afeta é o fato de não ter as informações: O cartão, a forma de pagamento e as parcelas. Certo?

Tentei acessar a URL https://hookbin.com/bin/Z8abPwXo e recebi um 404.

Achei melhor dividir esse tópico em partes, acho que vai ficar melhor, tudo bem pra você?

Obrigado pelo feedback

\o/ \o/ \o.

**Comment by magnocosta** [comment]
@frekele,

Criei as issues acima na tentativa de organizar melhor os pontos e para as threads não ficarem confusas quando outras pessoas tiverem as mesmas dúvidas.

E mais uma vez muito obrigado pelo feedback.

Abs!

**Comment by frekele** [comment]
@magnocosta 

concordo, eu somente copiei o ticket que foi criado no portal no devcielo.zendesk.com para essa issue.

Fica bem melhor mesmo, dividir os assuntos.

Sobre a url de captura https://hookbin.com/bin/Z8abPwXo , parece que o site https://hookbin.com está caindo hoje, vou criar uma nova url de captura para meus testes de integração.

vou fechar essa issue também, e conversão através das outras.

Obrigado

**Comment by magnocosta** [comment]
Belezaa !!!
